:technologist: Present docs output logs as the error output in CI

diff --git a/.github/workflows/docs.yml b/.github/workflows/docs.yml
--- a/.github/workflows/docs.yml
+++ b/.github/workflows/docs.yml
@@ -51,10 +51,18 @@ jobs:
         run: wget https://raw.githubusercontent.com/libhal/ci/main/doxygen.conf -O doxygen.conf
 
       - name: 📖 Run Doxygen
-        uses: mattnotmitt/doxygen-action@v1
+        uses: mattnotmitt/doxygen-action@v1.12.0
+        continue-on-error: true
         with:
           doxyfile-path: "doxygen.conf"
 
+      # Save the exit code of the last step (Doxygen run)
+      - name: 🧪 Capture Doxygen exit code
+        id: capture_doxygen_exit_code
+        run: echo "::set-output name=exit_code::$?"
+        shell: bash
+
+      # Conditionally read out any doxygen warnings only if the previous step failed
       - name: ⚠️ Read out any doxygen warnings
-        if: always()
-        run: cat doxygen_warn.log
+        if: ${{ steps.capture_doxygen_exit_code.outputs.exit_code == '1' }}
+        run: cat doxygen_warn.log | exit 1
